### ISSUE TITLE
unable to run the tool

### ISSUE THREAD

**Issue by vigneshjayavel** [singer-io/tap-fixerio#1]
`~ tap-fixerio
Traceback (most recent call last):
  File "/Users/vikki/.pyenv/versions/3.2/bin/tap-fixerio", line 9, in <module>
    load_entry_point('tap-fixerio==0.1.0', 'console_scripts', 'tap-fixerio')()
  File "build/bdist.macosx-10.12-x86_64/egg/pkg_resources/__init__.py", line 558, in load_entry_point
  File "build/bdist.macosx-10.12-x86_64/egg/pkg_resources/__init__.py", line 2682, in load_entry_point
  File "build/bdist.macosx-10.12-x86_64/egg/pkg_resources/__init__.py", line 2355, in load
  File "build/bdist.macosx-10.12-x86_64/egg/pkg_resources/__init__.py", line 2361, in resolve
  File "/Users/vikki/.pyenv/versions/3.2/lib/python3.2/site-packages/tap_fixerio.py", line 8, in <module>
    import requests
  File "/Users/vikki/.pyenv/versions/3.2/lib/python3.2/site-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/Users/vikki/.pyenv/versions/3.2/lib/python3.2/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 169
    for prefix in [u'*.', u'.']:
                       ^
SyntaxError: invalid syntax`

env detail:
~ pyenv --version
pyenv 1.0.8
~ python --version
Python 3.2
~ pip --version
pip 7.1.2 from /Users/vikki/.pyenv/versions/3.2/lib/python3.2/site-packages/pip-7.1.2-py3.2.egg (python 3.2)

**Comment by vigneshjayavel** [comment]
switching to python 2.7.13 solved the issue.
